language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# command to run tests
script:
  - pytest tests/test_api.py::TestApi  # <== This runs in Pipenv (a/k/a virtualenv)
