language: python

python:
  - "3.8"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install -e ".[testing]"

# command to run tests
script:
  - pytest tests/test_api.py::TestApi --doctest-modules -v --cov book_manager --cov-report term-missing # <== This runs in Pipenv (a/k/a virtualenv)

#coveralls.io  
after_success:
  - coveralls
